src/db/TagDataBean.java
admin jsp/handler/UserDBBean 변경
db.xml-namespace:DB로 임의 변경
=> admin changed

WebContent/svc/setting.jsp, build/classes/db/db.xml, src/db/TbDBBean.java, src/db/db.xml, src/handler/SvcDelHandler.java, src/handler/SvcFormHandler.java, src/handler/SvcProHandler.java, src/handler/SvcViewHandler.java
=> Board Works

WebContent/adm/album.jsp, WebContent/adm/comment.jsp, WebContent/adm/commentDel.jsp, WebContent/adm/head.jsp, WebContent/adm/script.js, WebContent/adm/setting.jsp, WebContent/adm/style_admin.css, WebContent/adm/tag.jsp, WebContent/adm/tagDel.jsp, WebContent/adm/trip.jsp, WebContent/adm/tripDel.jsp, WebContent/adm/user.jsp, WebContent/adm/userDel.jsp, WebContent/svc/album.jsp, WebContent/svc/loginForm.jsp, WebContent/svc/loginPro.jsp, WebContent/svc/script.js, build/classes/db/db.xml, src/db/CmtDBBean.java, src/db/CmtDataBean.java, src/db/TagDBBean.java, src/db/TbDBBean.java, src/db/TripDBBean.java, src/db/UserDBBean.java, src/db/db.xml, src/handler/AdmDelHandler.java, src/handler/AdmListHandler.java, src/handler/AdmTagHandler.java, src/handler/SvcFormHandler.java, src/handler/SvcProHandler.java
1.게시물관리 -게시물 페이지에서 직접 들어가서 관리하는 것을 제외하고 완료
2. 태그관리/회원관리 완료
3.loginForm.go 에서 user_level=9인 admin계정으로 로그인 가능
(requestmapping "/loginForm"/으로 변경)
4.album관리 x(파일 업로드가 선행되어야 가능할 것 같음)
=> admin changed(추석)

WebContent/svc/list.jsp, build/classes/db/db.xml, src/db/TbDBBean.java, src/db/db.xml, src/handler/SvcProHandler.java, src/handler/SvcViewHandler.java
=> board second

WebContent/adm/commentDel.jsp, WebContent/adm/tagDel.jsp, WebContent/adm/tripDel.jsp, WebContent/adm/userDel.jsp, WebContent/svc/album.jsp, WebContent/svc/script.js, WebContent/svc/setting.jsp, WebContent/svc/tripWriteForm.jsp, src/db/db.xml, src/handler/AdmListHandler.java
admin minor 수정& 사진 다운로드 밑작업
TripWriteForm에 지도  띄우는 키 추가(css 조정 및  정보 가공 필요)
key=AIzaSyBnBlipOjNesyFkAIAlXO9WkkIhfiqUIi4
=> minor 수정+지도 api key 추가

WebContent/svc/album.jsp, WebContent/svc/boardAlbum.jsp, WebContent/svc/boardAlbumPro.jsp, WebContent/svc/script.js, WebContent/svc/tripView.jsp, src/handler/SvcFormHandler.java, src/handler/SvcProHandler.java, src/handler/SvcViewHandler.java
1.tripView에서 album& 지도 띄움(album paging 처리 추후)
2.requestMapping은 trip으로 함
=> tripView 작성

WebContent/svc/script.js, WebContent/svc/setting.jsp, WebContent/svc/tripView.jsp, src/db/CmtDBBean.java, src/db/CmtDataBean.java, src/db/db.xml, src/handler/SvcProHandler.java
=> TripViewComment

WebContent/adm/setting.jsp, WebContent/adm/tagAdd.jsp, WebContent/adm/tagMod.jsp, WebContent/svc/boardAlbum.jsp, WebContent/svc/boardAlbumPro.jsp, WebContent/svc/loginPro.jsp, WebContent/svc/script.js, src/handler/AdmListHandler.java, src/handler/SvcProHandler.java, src/handler/SvcViewHandler.java
albumPro수정
download.go 추가(선택 파일 zip파일로 다운로드)
=> svcProHandler 수정 및 추가

WebContent/svc/boardAlbum.jsp, WebContent/svc/script.js, src/db/AlbumDBBean.java, src/db/db.xml, src/handler/SvcProHandler.java
사진 1개만 선택한 경우 파일로 저장
체크 박스 선택해서 zip file로 다운 및 게시판 전체 앨범 다운로드 가능
=> album download 수정 완료

WebContent/svc/myPage.jsp, WebContent/svc/userModify.jsp, build/classes/db/db.xml, src/db/TagDBBean.java, src/db/db.xml, src/handler/SvcFormHandler.java, src/handler/SvcViewHandler.java
=> myPage Tag first

WebContent/svc/script.js, src/db/LocDBBean.java, src/db/LocDataBean.java, src/db/db.xml, src/handler/SvcFormHandler.java, src/handler/SvcProHandler.java
=> writeform 작성시 좌표값 추가

WebContent/svc/userModify.jsp, build/classes/db/db.xml, src/db/TagDBBean.java, src/db/db.xml, src/handler/SvcFormHandler.java
=> tag second

WebContent/svc/script.js, WebContent/svc/trip.jsp, src/handler/SvcProHandler.java, src/handler/SvcViewHandler.java
=> CommemtUpdate

WebContent/svc/script.js, src/db/db.xml, src/handler/SvcProHandler.java
=> writePro 1차 완료

WebContent/adm/trip.jsp, WebContent/adm/tripDel.jsp, WebContent/svc/header.jsp, WebContent/svc/script.js, WebContent/svc/setting.jsp, WebContent/svc/trip.jsp, WebContent/svc/tripDel.jsp, WebContent/svc/tripWrite.jsp, src/db/TripDBBean.java, src/db/db.xml
1.adminpage 게시물 관리에서 글 내용 클릭 시 게시물 들어가서 보기 간ㅇ
2. 게시물 삭제 2차 완료
=> admin page연결 및 게시물 삭제

WebContent/svc/myPage.jsp, WebContent/svc/setting.jsp, WebContent/svc/userLeave.jsp, WebContent/svc/userLeavePro.jsp, src/db/UserDBBean.java, src/db/db.xml
=> userDelete

WebContent/svc/userLeavePro.jsp, build/classes/db/db.xml, src/db/TbDBBean.java
=> bug fix again!!!

WebContent/svc/script.js, WebContent/svc/trip.jsp, src/db/CmtDataBean.java, src/db/TbDBBean.java, src/handler/SvcProHandler.java
=> comment exception handling

WebContent/svc/emailCheck.jsp, WebContent/svc/registration.jsp, WebContent/svc/script.js, src/handler/SvcProHandler.java
=> user태그부분 수정

src/db/TbDBBean.java, src/db/db.xml, src/handler/SvcFormHandler.java, src/handler/SvcViewHandler.java
=> List count

WebContent/svc/Conditions.jsp, WebContent/svc/script.js, WebContent/svc/tripWrite.jsp
=> userUpdate

WebContent/svc/script.js
=> commentUpdate
